export const EventFilterTypes = {
  SPECIAL: 'special',
  LATEST: 'latest',
  TREND: 'trend'
}

export const JoinEventStep = {
  BEGIN: 'BEGIN',
  SELECT_PAYMENT: 'SELECT_PAYMENT',
  ADD_CREDIT: 'ADD_CREDIT',
  ADD_CREDIT_DONE: 'ADD_CREDIT_DONE',
  DONE: 'DONE'
}

export const EventStatus = {
  OPENING: 'OPENING',
  CLOSED: 'CLOSED',
  CLOSE_FAILED: 'CLOSE_FAILED',
  PROFIT_CONFIRMING: 'PROFIT_CONFIRMING',
  PROFIT_CONFIRMED: 'PROFIT_CONFIRMED',
  PROFIT_CONFIRM_FAILED: 'PROFIT_CONFIRM_FAILED',
  CANCELLED: 'CANCELLED'
}
